#源镜像
FORM openjdk:8

#作者信息
MAINTAINER yangz

#暴露端口
EXPOSE 8080

#工作目录(指定在创建容器后，终端默认登陆的进来工作目录，一个落脚点)
WORKDIR /root

#复制宿主机目录下的jar包到启动后容器的指定位置 
COPY jarfile/*.jar /root/jarfile/app.jar

#启动容器成功后执行命令
ENTRYPOINT ["java","-jar","/root/jarfile/app.jar"]
